services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-frontend
    env_file:
      - .env
    ports:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-app.rule=Host(`${FRONTEND_DOMAIN}`)
      - traefik.http.routers.frontend-app.entrypoints=websecure
      - traefik.http.routers.frontend-app.tls.certResolver=letsencrypt
      - traefik.http.services.frontend-app.loadbalancer.server.port=3000
    volumes:
      - eisenhower-data:/data
    restart: unless-stopped

volumes:
  eisenhower-data:
